### ISSUE TITLE
Warn user when entering a existing seed packet id

### ISSUE THREAD

**Issue by LaurieKoudstaal** [BlueWrenSoftware/seedB.js#21]
Warn user that they will overwrite an existing record, if they enter a seed packet ID that already exists in the system

**Comment by dkoudstaal** [comment]
The quickest would be with the use of an alert pop-up

**Comment by LaurieKoudstaal** [comment]
@dkoudstaal , please close if you are hppy with my solution

**Comment by dkoudstaal** [comment]
created dialog modal
