### ISSUE TITLE
Change submit button appearance depending on create/edit seed packet

### ISSUE THREAD

**Issue by LaurieKoudstaal** [BlueWrenSoftware/seedB.js#22]
If a seed packet id already exists, make the submit button change from a "create" button to an "edit" button (maybe using colouring and icons).

**Comment by dkoudstaal** [comment]
button images are now different
![image](https://user-images.githubusercontent.com/8015790/222996085-d5d4eb36-7508-4f32-9adc-34641f888669.png)
