### ISSUE TITLE
Edit Screen: Seed Packet ID first

### ISSUE THREAD

**Issue by LaurieKoudstaal** [BlueWrenSoftware/seedB.js#23]
Put seed packet ID entry first (as it it's sth emost required field)

**Comment by dkoudstaal** [comment]
Done. Do you want this for the table as well?

**Comment by dkoudstaal** [comment]
Fixed. Also ordered the order of the other columns.
order is:
Packet Id, variety, group, num, gram, cost, date, edit

**Comment by dkoudstaal** [comment]
fixed the new order in both the form and the table
