### ISSUE TITLE
Change the toolbar buttons depending on the screen

### ISSUE THREAD

**Issue by LaurieKoudstaal** [BlueWrenSoftware/seedB.js#25]
Some buttons arent relevant to all screens.  The following is a list screens and the buttons that are relevant for that screen:
Packet List:
- Help
- Database Maintenance
- Create new record
- Reload (?)
- Jump to bottom
Create/Edit Packet:
 - Home
 - Help
 - Next record
 - Previous record
 - Create new record
 - Duplicate record
 - Reload
 - Save
 - Delete
DB Maintenance
 - Home
 - Help

**Comment by dkoudstaal** [comment]
![image](https://user-images.githubusercontent.com/8015790/219558549-21e14881-d17b-4746-aa68-4294c3e1251f.png)
created home page button menu

**Comment by dkoudstaal** [comment]
fixed
