### ISSUE TITLE
Remove "help" button

### ISSUE THREAD

**Issue by LaurieKoudstaal** [BlueWrenSoftware/seedB.js#27]
Most people won't read a help page, anyway.  Tool-tips are probably sufficient

**Comment by dkoudstaal** [comment]
You might be right. I was thinking of the help button link to a specific item and tnen going back  to the item

**Comment by dkoudstaal** [comment]
decided to have just a documentation page which could function as a help page but not a right click help on specific feature. Those are removed from the page
